#############################################################################
# Makefile for building: GrblController
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  GCV.pro
# Template: app
# Command: o:/DevCpp/Qt-5.3/5.2.0/mingw48_32/bin/qmake.exe -config debug -spec win32-g++ -o Makefile GCV.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = o:/DevCpp/Qt-5.3/5.2.0/mingw48_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: GCV.pro O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/win32-g++/qmake.conf O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/spec_pre.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/qdevice.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/device_config.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/common/shell-unix.conf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/qconfig.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axbase.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axbase_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axserver.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axserver_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bluetooth.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_clucene_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_core.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_core_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_declarative.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_declarative_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designer.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designer_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_gui.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_gui_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_help.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_help_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_network.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_network_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_nfc.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_nfc_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_opengl.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_opengl_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_positioning.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_positioning_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qml.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qml_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quick.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quick_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_script.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_script_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sensors.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sensors_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_serialport.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_serialport_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sql.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sql_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_svg.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_svg_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_testlib.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_testlib_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_uitools.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_uitools_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkit.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkit_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_widgets.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_widgets_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_winextras.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_winextras_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xml.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xml_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/qt_functions.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/qt_config.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/win32-g++/qmake.conf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/spec_post.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/exclusive_builds.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/default_pre.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/default_pre.prf \
		QextSerialPort/qextserialport.pri \
		log4qt/log4qt.pri \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/resolve_config.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/exclusive_builds_post.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/default_post.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/rtti.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/warn_on.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/qt.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/resources.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/moc.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/opengl.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/uic.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/windows.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/testcase_targets.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/exceptions.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/yacc.prf \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/lex.prf \
		GCV.pro \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5OpenGL.prl \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5PrintSupport.prl \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Widgets.prl \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Xml.prl \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Gui.prl \
		O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Core.prl
	$(QMAKE) -config debug -spec win32-g++ -o Makefile GCV.pro
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/spec_pre.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/qdevice.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/device_config.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/common/shell-unix.conf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/qconfig.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axbase.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axbase_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axserver.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axserver_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bluetooth.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_clucene_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_concurrent_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_core.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_core_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_declarative.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_declarative_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designer.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designer_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_gui.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_gui_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_help.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_help_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimedia_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_network.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_network_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_nfc.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_nfc_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_opengl.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_opengl_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_positioning.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_positioning_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_printsupport_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qml.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qml_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmltest_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quick.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quick_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_script.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_script_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_scripttools_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sensors.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sensors_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_serialport.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_serialport_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sql.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sql_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_svg.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_svg_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_testlib.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_testlib_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_uitools.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_uitools_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkit.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkit_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_widgets.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_widgets_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_winextras.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_winextras_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xml.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xml_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/qt_functions.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/qt_config.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/win32-g++/qmake.conf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/spec_post.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/exclusive_builds.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/default_pre.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/default_pre.prf:
QextSerialPort/qextserialport.pri:
log4qt/log4qt.pri:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/resolve_config.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/exclusive_builds_post.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/default_post.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/rtti.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/warn_on.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/qt.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/resources.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/moc.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/opengl.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/uic.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/win32/windows.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/testcase_targets.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/exceptions.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/yacc.prf:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/mkspecs/features/lex.prf:
GCV.pro:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5OpenGL.prl:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5PrintSupport.prl:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Widgets.prl:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Xml.prl:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Gui.prl:
O:/DevCpp/Qt-5.3/5.2.0/mingw48_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -config debug -spec win32-g++ -o Makefile GCV.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
